/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Screen;

/**
 *
 * @author meimei
 */
public class UserManualView extends javax.swing.JPanel {

    /**
     * Creates new form UserManualView
     */
    public UserManualView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        label2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("USER MANUAL");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setText("1. Chỉnh sửa ngân sách\n- Người dùng bắt đầu thực hiện chức năng bằng nhấn vào mục Quản lý và chọn Ngân sách. \n- Người dùng nhập vào mã ngân sách, tên ngân sách và số tiền khả dụng của ngân sách đó, nhấn nút thêm để thêm ngân sách.\n- Người dùng chọn bất kỳ một ngân sách nào đó và nhấn nút sửa để chỉnh sửa ngân sách.\n- Người dùng chọn bất kỳ một ngân sách nào đó và nhấn nút xóa để xóa ngân sách.\n2. Chỉnh sửa danh mục chi tiêu\n- Người dùng bắt đầu thực hiện chức năng bằng nhấn vào mục Quản lý và chọn Danh mục. \n- Người dùng nhập vào mã danh mục, tên danh mục của danh mục đó, nhấn nút thêm để thêm danh mục.\n- Người dùng chọn bất kỳ một danh mục nào đó và nhấn nút sửa để chỉnh sửa danh mục.\n- Người dùng chọn bất kỳ một danh mục nào đó và nhấn nút xóa để xóa danh mục.\n3. Tạo chi tiêu\n- Người dùng bắt đầu thực hiện chức năng bằng nhấn vào nút Tạo chi tiêu. \n- Người dùng nhập vào số tiền, chọn danh mục, ngân sách và cuối cùng nhập ngày tạo để thêm chi tiêu.\n- Thêm ghi chú nếu cần.\n4. Tạo thu nhập\n- Người dùng bắt đầu thực hiện chức năng bằng nhấn vào nút Tạo thu nhập. \n- Người dùng nhập vào số tiền, chọn danh mục, ngân sách và cuối cùng nhập ngày tạo để thêm thu nhập.\n- Thêm ghi chú nếu cần.\n5. Lọc giao dịch\n- Thực hiện lọc giao dịch bằng cách lựa chọn danh mục, ngân sách, tháng năm tương ứng.\n- Nhấn nút Lọc để thực hiện lọc danh sách, Nhấn nút Xóa Lọc để xóa bộ lọc hiện tại.\n");
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusTraversalKeysEnabled(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jTextPane1.setRequestFocusEnabled(false);
        jTextPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(519, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
