/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;

import Coordinator.AddGiaoDichCoordinator;
import DAO.DanhMucDAO;
import DAO.GiaoDichDAO;
import DAO.NganSachDAO;
import Database.DanhMuc;
import Database.GiaoDich;
import Database.NganSach;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;

public class CreateGiaoDichView extends javax.swing.JFrame {
    boolean isChiTieu;
    ArrayList<NganSach> nganSachs;
    ArrayList<DanhMuc> danhMucs;
    AddGiaoDichCoordinator coordinator;
    
    public CreateGiaoDichView(boolean isChiTieu, AddGiaoDichCoordinator coordinator) {
        this.isChiTieu = isChiTieu;
        this.coordinator = coordinator;
        
        initComponents();
        getDanhMucCB();
        getNganSachCB();
        updateTitleLabel();
    }
    
    private void updateTitleLabel() {
        String text = this.isChiTieu ? "TẠO CHI TIÊU MỚI" : "TẠO THU NHẬP MỚI";
        titleLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneyTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        danhMucCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nganSachCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        createdDayTF = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTF = new javax.swing.JTextPane();
        createButton = new java.awt.Button();
        cancelButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLabel.setText("THÊM GIAO DỊCH");

        jLabel3.setText("Số tiền");

        jLabel4.setText("Danh mục");

        danhMucCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhMucCBActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngân sách");

        jLabel5.setText("Ngày tạo");

        jLabel7.setText("Ghi chú");

        jScrollPane1.setViewportView(noteTF);

        createButton.setActionCommand("Thêm");
        createButton.setBackground(new java.awt.Color(255, 204, 51));
        createButton.setLabel("Thêm");
        createButton.setSize(new java.awt.Dimension(70, 30));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setActionCommand("Huỷ");
        cancelButton.setBackground(new java.awt.Color(204, 204, 204));
        cancelButton.setLabel("Huỷ");
        cancelButton.setSize(new java.awt.Dimension(70, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moneyTF)
                            .addComponent(danhMucCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nganSachCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createdDayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(titleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createdDayTF, danhMucCB, moneyTF, nganSachCB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(danhMucCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nganSachCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(createdDayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {danhMucCB, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel6, nganSachCB});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createdDayTF, jLabel5});

        createButton.getAccessibleContext().setAccessibleName("Thêm");
        cancelButton.getAccessibleContext().setAccessibleName("Huỷ");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void danhMucCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhMucCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danhMucCBActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String message = "Bạn có chắc chắn muốn thêm không?";
        String money = moneyTF.getText();
        String note = noteTF.getText();
        int selectedDanhMuc = danhMucCB.getSelectedIndex();
        int selectedNganSach = nganSachCB.getSelectedIndex();
        double moneyValue;
        
        // Kiem tra 
        if (money.isEmpty()) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng nhập số tiền.");
            return;
        }
        
        try {
            moneyValue = Double.parseDouble(money);
            
            // Đưa về số dương 
            if (moneyValue < 0) {
                moneyValue = -moneyValue;
            }
            
            // Nếu đây là chi tiêu thì số tiền khi thêm vào database sẽ là âm 
            if (this.isChiTieu) {
                NganSach ns = nganSachs.get(selectedNganSach);
                if (moneyValue > ns.getMoney()) {
                    message = "Số tiền bạn chi đang vượt quá ngân sách, " + message;
                }
                moneyValue = -moneyValue;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng nhập đúng định dạng của số tiền.");
            return;
        }
        
        if (createdDayTF.getDate() == null) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng chọn ngày.");
            return;
        }
        
        if (selectedNganSach == -1) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng chọn ngân sách.");
            return;
        }
        
        if (selectedDanhMuc == -1 && this.isChiTieu) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng chọn danh mục.");
            return;
        }
        
        // Hien thi dialog xac nhan 
        int response = JOptionPane.showConfirmDialog(null, message, "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (response == 1) {
            return;
        }
        
        java.sql.Date date;
        date = new java.sql.Date(createdDayTF.getDate().getTime());

        try {
            GiaoDich instance = new GiaoDich();

            if (selectedDanhMuc != -1) {
                instance.danhMucID = danhMucs.get(selectedDanhMuc).getID();
            } else {
                instance.danhMucID = 0;
            }

            instance.nganSachID = nganSachs.get(selectedNganSach).getID();
            instance.note = note;
            instance.createdDay = date;
            instance.money = moneyValue;
            GiaoDichDAO.insertWithAnotherDate(instance);

            JOptionPane.showMessageDialog(getContentPane(), "Thêm thành công");
            this.coordinator.stop();
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.coordinator.stop();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void getDanhMucCB() {
        danhMucCB.removeAllItems();

        try {
            danhMucs = DanhMucDAO.getAll();
            for (DanhMuc danhMuc : danhMucs) {
                danhMucCB.addItem(danhMuc.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        danhMucCB.setSelectedIndex(-1);
    }
    
    public void getNganSachCB() {
        nganSachCB.removeAllItems();

        try {
            nganSachs = NganSachDAO.getAll();
            for (NganSach nganSach : nganSachs) {
                nganSachCB.addItem(nganSach.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        nganSachCB.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cancelButton;
    private java.awt.Button createButton;
    private com.toedter.calendar.JDateChooser createdDayTF;
    private javax.swing.JComboBox<String> danhMucCB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moneyTF;
    private javax.swing.JComboBox<String> nganSachCB;
    private javax.swing.JTextPane noteTF;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
