/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;

import Coordinator.UpdateGiaoDichCoordinator;
import DAO.DanhMucDAO;
import DAO.GiaoDichDAO;
import DAO.NganSachDAO;
import Database.DanhMuc;
import Database.GiaoDich;
import Database.NganSach;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UpdateGiaoDichView extends javax.swing.JFrame {

    GiaoDich gd;
    UpdateGiaoDichCoordinator coordinator;
    ArrayList<NganSach> nganSachs;
    ArrayList<DanhMuc> danhMucs;
    /**
     * Creates new form UpdateGiaoDichView
     */
    public UpdateGiaoDichView(GiaoDich gd, UpdateGiaoDichCoordinator coordinator) {
        this.coordinator = coordinator;
        this.gd = gd;
        initComponents();
        
        getDanhMucCB();
        getNganSachCB();
        setValueForAllFields();
        updateTitle();
    }
    
    private void updateTitle() {
        String text = gd.money > 0 ? "CHỈNH SỬA THU NHẬP" : "CHỈNH SỬA CHI TIÊU";
        titleLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        moneyTF = new javax.swing.JTextField();
        danhMucCB = new javax.swing.JComboBox<>();
        nganSachCB = new javax.swing.JComboBox<>();
        createdDayTF = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTF = new javax.swing.JTextPane();
        updateButton = new java.awt.Button();
        deleteButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLabel.setText("CHỈNH SỬA GIAO DỊCH");

        jLabel2.setText("Mã giao dịch");

        jLabel3.setText("Số tiền");

        jLabel4.setText("Danh mục");

        jLabel5.setText("Ngày tạo");

        jLabel6.setText("Ngân sách");

        jLabel7.setText("Ghi chú");

        idTF.setEnabled(false);

        danhMucCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhMucCBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(noteTF);

        updateButton.setBackground(new java.awt.Color(255, 204, 51));
        updateButton.setLabel("Sửa");
        updateButton.setSize(new java.awt.Dimension(70, 30));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setLabel("Xoá");
        deleteButton.setSize(new java.awt.Dimension(70, 30));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTF)
                            .addComponent(moneyTF)
                            .addComponent(danhMucCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nganSachCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createdDayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(titleLabel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(danhMucCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nganSachCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(createdDayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String money = moneyTF.getText();
        String id = idTF.getText();
        String note = noteTF.getText();
        int selectedDanhMuc = danhMucCB.getSelectedIndex();
        int selectedNganSach = nganSachCB.getSelectedIndex();
        
        double moneyValue;
        
        // Kiem tra
        if (money.isEmpty()) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng nhập số tiền.");
            return;
        }
         
        try {
           moneyValue = Double.parseDouble(money);
           
           if (moneyValue < 0) {
                moneyValue = -moneyValue;
            }
            
            if (this.gd.money <= 0) {
                moneyValue = -moneyValue;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng nhập đúng định dạng của số tiền.");
            return;
        }

        if (createdDayTF.getDate() == null) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng chọn ngày.");
            return;
        }
        
        if (selectedDanhMuc == -1 && gd.money <= 0) {
            JOptionPane.showMessageDialog(getContentPane(), "Vui lòng chọn danh mục.");
            return;
        }
   
        // Hien thi thong bao xac nhan
        int response = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa không?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (response == 1) {
            return;
        }
        
        java.sql.Date date;
        date = new java.sql.Date(createdDayTF.getDate().getTime());
        
        try {
           GiaoDich instance = new GiaoDich();
           instance.id = Integer.parseInt(id);
           
           if (selectedDanhMuc != -1) {
               instance.danhMucID = danhMucs.get(selectedDanhMuc).getID();
           } else {
               instance.danhMucID = 0;
           }
           
           instance.nganSachID = nganSachs.get(selectedNganSach).getID();
           instance.note = note;
           instance.createdDay = date;
           instance.money = moneyValue;
           GiaoDichDAO.update(instance);
           
           JOptionPane.showMessageDialog(getContentPane(), "Sửa thành công");
           this.coordinator.stop();
       } catch (SQLException e) {
           e.printStackTrace();
       }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá không?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (response == 1) {
            return;
        }
        
        try {
            String id = idTF.getText();
            GiaoDichDAO.delete(Integer.parseInt(id));
            JOptionPane.showMessageDialog(getContentPane(), "Xoá thành công");
            this.coordinator.stop();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateGiaoDichView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void danhMucCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhMucCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danhMucCBActionPerformed

    public void getDanhMucCB() {
        danhMucCB.removeAllItems();

        try {
            danhMucs = DanhMucDAO.getAll();
            for (DanhMuc danhMuc : danhMucs) {
                danhMucCB.addItem(danhMuc.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        danhMucCB.setSelectedIndex(-1);
    }
    
    public void getNganSachCB() {
        nganSachCB.removeAllItems();

        try {
            nganSachs = NganSachDAO.getAll();
            for (NganSach nganSach : nganSachs) {
                nganSachCB.addItem(nganSach.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        nganSachCB.setSelectedIndex(-1);
    }
    
    private void setValueForAllFields() {
        idTF.setText(Integer.toString(gd.id));
        moneyTF.setText(Double.toString(gd.money));
        createdDayTF.setDate(gd.createdDay);
        noteTF.setText(gd.note);
        
        for (int i = 0; i < nganSachs.size(); i++) {
            if (nganSachs.get(i).getID() == gd.nganSachID) {
                nganSachCB.setSelectedIndex(i);
                break;
            }
        }
        
        for (int i = 0; i < danhMucs.size(); i++) {
            if (danhMucs.get(i).getID() == gd.danhMucID) {
                danhMucCB.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser createdDayTF;
    private javax.swing.JComboBox<String> danhMucCB;
    private java.awt.Button deleteButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moneyTF;
    private javax.swing.JComboBox<String> nganSachCB;
    private javax.swing.JTextPane noteTF;
    private javax.swing.JLabel titleLabel;
    private java.awt.Button updateButton;
    // End of variables declaration//GEN-END:variables

}
